### ISSUE TITLE
Cannot post new ad; API error "Cannot unmarshal content"

### ISSUE THREAD

**Issue by jackm** [rybodiddly/Kijiji-Reposter#1]
I attempted to post a new ad from the /post page after logging into the web interface, but this fails and Flask dumps the stack trace.

The problem is after during the call to _submitFunction_, the Kijiji site returns an API error message: "Cannot unmarshal content" with HTTP status code 400.

**Comment by rybodiddly** [comment]
For which category? And would you mind posting the title / description, or email it to me so I can perform some tests. Still working out a few bugs. But i find the unmarshlled content missing attributes or complex character sets.

**Comment by jackm** [comment]
The problem was on my end, I edited some of the server code which caused a bug.
