### ISSUE TITLE
Incorrect Location via Postal Code

### ISSUE THREAD

**Issue by resiproxy** [rybodiddly/Kijiji-Reposter#10]
So the ad posts perfectly fine and includes the postal code, But when you open the ad and click on the postal code that is there it directs you to the middle of the ocean.

Manually updating the postal code corrects the issue and i see that it includes the and province as well, not sure if some extra validation needs to take place

**Comment by rybodiddly** [comment]
Interesting. Thanks for pointing this one out. Will investigate. I currently haven't experienced this issue, but have noticed it with other peoples ads in general that are even posting normally without any kind of reposting utility.

**Comment by rybodiddly** [comment]
Upon further inspection, the payload sent by the reposter is identical to that sent by the kijji app. The analysis of the traffic also doesn't indicate that any additional information has been uploaded. What I did notice, is that when an ad is initially posted, for a short while it only shows the Postal Code, and if you click on the map it ends up in the ocean. But after waiting 15 mins, then refreshing the page, the ad showed the full address and the map worked.

So my guess, is that it's a backend issue with the kijiji mingle server that takes time to connect the location id, postal code etc. with the map coordinates.

**Comment by rybodiddly** [comment]
Update: Verified there is a 5 - 6 minute delay for map coordinates to be applied to your ad. So this is nothing to do with the reposter, it is entirely a kijiji server delay.
