### ISSUE TITLE
Reposting doesn’t work

### ISSUE THREAD

**Issue by yunners** [rybodiddly/Kijiji-Reposter#11]
Ad posted fine, but reposting at 8:00 AM and 5:00 PM both missed by the app. Any particular fix?

**Comment by rybodiddly** [comment]
1. look at the terminal output for errors that would indicate errors with the reposting and post them here for analysis.
2. is your system clock correctly set?

**Comment by rybodiddly** [comment]
closing this issue since you have not responded in almost 5 months.
