### ISSUE TITLE
Add tags to the listing

### ISSUE THREAD

**Issue by abdulzeedo** [rybodiddly/Kijiji-Reposter#12]
Category: Services -> Tutoring 

I cannot add any tags to my listing using the *Post* page. 

Tags are crucial to pop up in the Kijiji search! Also, a one repost button would be helpful too!

**Comment by rybodiddly** [comment]
Will look into the tags. Shouldn't be too difficult.
Not sure what you mean by a one repost button? Could you clarify?

**Comment by rybodiddly** [comment]
After analysis of the traffic regarding tag attributes under the services categories, it was discovered that they simply do not exist on the mobile version. This reposter uses the kijiji mobile api, not the web api. If you post a service using the mobile app, there are no tag options. The kijiji reposter app uses a dynamic attribute generator that takes the attributes directly from the kijiji mobile server and generates a posting page on the fly, meaning it's always up to date. So looks like you're out of luck until they add a tags option to the mobile app.

**Comment by rybodiddly** [comment]
marking this as closed, as the issue lies with kijiji's mingle server, not the reposter.
