### ISSUE TITLE
Idea for expanding project

### ISSUE THREAD

**Issue by DudeManGuy0** [rybodiddly/Kijiji-Reposter#13]
Would you be willing to accept a push to include functions for automatically scraping and filtering listings from Kijiji and notifying end user of new listings which pass the filter? You can see this more in-depth in my project if you want. I'll rewrite the code to Python and I think it'd be a cool idea to have this tool that can do all these useful features.

**Comment by rybodiddly** [comment]
Could be a viable feature, but if only done using the mobile api, not web scraping. This project utilizes the mobile api (check kijjiapi.py) used with kijiji's mingle server. If you would like to add something of that nature, use a mitm to capture mobile api calls for search functions etc. and build off that.
