### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hilly77b** [rybodiddly/Kijiji-Reposter#15]
I'm getting this error when trying to post an ad in the Real Estate > Real Estate Services, as well as other locations under Services page. 
![error](https://user-images.githubusercontent.com/89349650/130360648-c6bb5b24-37a8-4626-9951-ade9020a3e3e.png)

**Comment by rybodiddly** [comment]
will take a look at this over the next few days. requires a bit of work to monitor packets to see if anything has changed on kijiji's end.

**Comment by rybodiddly** [comment]
Tested and was able to post the the Real Estate Services category without issue. Check console / terminal window for an error code from the kijiji server. Will let you know why the ad failed to post. If the ad description has less than 10 characters it will fail to post. Also, certain characters / symbols cause issues with posting. Keep description simple.

**Comment by hilly77b** [comment]
Ok perfect thanks Rybo. I was posting in Services > Financial as well as
Real Estate > Real Estate Services. Will check your new update tonight when
I get home. Thanks again !

**Comment by rybodiddly** [comment]
> Is it possible to dump the Kijiji error code onto the web page when this happens?

The only issue I see there is that all responses coming from the kijiji mingle server have the status code 200 from what I recall. You had to actually pull the error code out of the xml response. As long as you take that into account, should be viable. If you want to take a crack at it, just make a pull request.
