### ISSUE TITLE
No edit button for existing ads on schedule

### ISSUE THREAD

**Issue by hilly77b** [rybodiddly/Kijiji-Reposter#16]
If you make a mistake on an ad it's super annoying because you have to re-create the whole ad. Add an edit button to edit an ad?

**Comment by rybodiddly** [comment]
You can just edit the json file for the ad.

**Comment by rybodiddly** [comment]
Yes, the ad files consist of the xml data sent to kijiji to post the ad. The schedules are in the static/schedules.json file and should be sorted by ad id #.
