### ISSUE TITLE
Listing fails to stay active after a 'successful' repost

### ISSUE THREAD

**Issue by freiheit950** [rybodiddly/Kijiji-Reposter#17]
For some listings, the application attempts to repost them, and it successfully does so (it even gets the new listing id from the server) but after a few seconds, it is taken down from kijiji.

It only happens with some listings, under the same account. It is very difficult to tell what is going on because again, the listing does get posted successfully for a couple of seconds. Right now failing under the category 15, but category 760 seems to be working fine.

Does anybody know what could be causing this issue? As far as the application is concerned, the listing gets reposted succesfully so its very difficult to debug.

**Comment by rybodiddly** [comment]
Found this thread which looks to address your issues: [Kijiji Listing Issue](https://github.com/ArthurG/Kijiji-Repost-Headless/issues/192)

**Comment by freiheit950** [comment]
Very informative, thanks. After lots of testing, it does seem like the category (and the account) is the issue and not the scripts. I have not had any issue with other categories. I will close now this thread.
