### ISSUE TITLE
Posting new ad fails with using certain locations

### ISSUE THREAD

**Issue by jackm** [rybodiddly/Kijiji-Reposter#2]
When posting a new ad, choosing certain geographic locations fails to post the ad.

This seems to happen because some locations are nested up to 4 levels deep (Country > Province > Metro Area > City) and others are just 3 levels deep (Country > Province > City). For example, nested under the "Ottawa / Gatineau Area" location are "Gatineau" and "Ottawa" locations.

The UI doesn't let you select the the most nested location (e.g. just "Ottawa" won't be an option), and when it attempts to submit the new ad to Kijiji, it rejects it and the API error message says that you must select a location. It would appear that it wants the most nested location IDs and not an ID further up. For example, if you attempt to post an ad to the "Ottawa / Gatineau Area" location, it will fail.

**Comment by rybodiddly** [comment]
Thanks for the insight and bug find. Just finished working on the conversations component and am currently updating the repository. I was moving things around, so you might want to delete the old fork and grab the new one.

Will work on adding support for 4th level nested locations over the next few days.

**Comment by rybodiddly** [comment]
Finished correcting the 4th level nested location issues. Fixes have been committed. Give it a test and let me know how it works.  If all is well, will mark this as closed.

**Comment by jackm** [comment]
Fix for the locations nested 4 levels deep appears to work now; I was able to post an ad this way without getting any API error messages.
