### ISSUE TITLE
ModuleNotFoundError: No module named 'pgeocode'

### ISSUE THREAD

**Issue by ssinfod** [rybodiddly/Kijiji-Reposter#23]
I recently did a fresh installation on Windows 10 and also on a Raspberry Pi

For both installations, I had an error on the first execution. (error: ModuleNotFoundError: No module named 'pgeocode')
```
pi@raspberrypi:~/Kijiji-Reposter $ python server.py
Traceback (most recent call last):
  File "/home/pi/Kijiji-Reposter/server.py", line 5, in <module>
    import pgeocode
ModuleNotFoundError: No module named 'pgeocode'
pi@raspberrypi:~/Kijiji-Reposter $

```

I resolve the issue by installation the package 'pgeocode' with the following command:
`pip3 install pgeocode
`

I think the pgeocode package should probably be added in requirements.txt.

**Comment by rybodiddly** [comment]
pgeocode was added to the readme.md but missed the requirements.txt. Has been added.
