### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by ssinfod** [rybodiddly/Kijiji-Reposter#25]
I tried to install Kijiji-Reposter on Windows 10 (64 bits)

I get the following error when I post my first add.

```
urllib.error.URLError
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

```
![image](https://user-images.githubusercontent.com/10925073/148627087-61d3cb84-6565-48d9-88ab-d276e22de525.png)

For now, as a quick ugly fix, I added the following two lines in the **server.py**

At line 19: 
`import ssl
`

At line 27 (just after app.secret_key):
`ssl._create_default_https_context = ssl._create_unverified_context
`

I'm not sure how to resolve this issue to correctly use SSL with Windows 10. 
Any suggestions ?

**Comment by rybodiddly** [comment]
starting at line `467`:
```
# Create Session with Http2.0 compatability for Kijiji separate from Flask local session
# SSL verification disabled to avoid ConnectionPool Max retries exception
# Need to implement this in future (httpx module still in alpha)
urllib3.disable_warnings()
timeout = httpx.Timeout(15.0, connect=30.0)
kijijiSession = httpx.Client(verify=False, timeout=timeout)
```
change: `kijijiSession = httpx.Client(verify=False, timeout=timeout)`
to: `kijijiSession = httpx.Client(timeout=timeout)`

You might also want to comment out `urllib3.disable_warnings()`.

That should re-enable ssl. But haven't tested on windows nor do I own a windows based pc.

**Comment by ssinfod** [comment]
It is working with 
`kijijiSession = httpx.Client(timeout=timeout)`

Thanks.
