### ISSUE TITLE
Type error when posting new ad

### ISSUE THREAD

**Issue by Connor2hd** [rybodiddly/Kijiji-Reposter#3]
Hello,

This looks great for reposting Kijiji ads but I am getting an error when trying to add a new add/post.

I am running this on a windows server in an Anaconda Python 3.7 environment with the required dependencies.

The error is:

`TypeError: 'NoneType' object is not subscriptable`

Stack trace:

`File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Administrator\anaconda3\envs\Kijiji2\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "P:\Scripts\Kijiji2\Kijiji-Reposter\server.py", line 555, in submit
Open an interactive python shell in this frameadID = parsed['ad:ad']['@id']`

**Comment by rybodiddly** [comment]
It means that the posting failed. Lots of updates have been committed over the last little while. So make sure you have the newest version downloaded. The newest version will post any kijiji api error to the console window. Would be helpful to have that if you're getting one. Also, it would be helpful to know what you're trying to post. If you look at the server.py file, there is a `debugMode=False` variable. If you set this to true, it will print the final ad submission to the console instead of sending it to kijiji. It would be helpful to know what's being sent, and the api error if you're getting one. That way I can test and see if I can replicate the issue.

**Comment by Connor2hd** [comment]
Thanks for getting back to me @rybodiddly .

Here is the ad payload from debug mode:

`<?xml version="1.0" encoding="utf-8"?>
<ad:ad xmlns:types="http://www.ebayclassifiedsgroup.com/schema/types/v1" xmlns:cat="http://www.ebayclassifiedsgroup.com/schema/category/v1" xmlns:loc="http://www.ebayclassifiedsgroup.com/schema/location/v1" xmlns:ad="http://www.ebayclassifiedsgroup.com/schema/ad/v1" xmlns:attr="http://www.ebayclassifiedsgroup.com/schema/attribute/v1" xmlns:pic="http://www.ebayclassifiedsgroup.com/schema/picture/v1" xmlns:user="http://www.ebayclassifiedsgroup.com/schema/user/v1" xmlns:rate="http://www.ebayclassifiedsgroup.com/schema/rate/v1" xmlns:reply="http://www.ebayclassifiedsgroup.com/schema/reply/v1" locale="en-CA">
        <ad:title>Buying Vintage Stereo Equipment</ad:title>
        <ad:description>Buying Vintage Stereo Equipment</ad:description>
        <loc:locations>
                <loc:location id="1700214"/>
        </loc:locations>
        <ad:ad-type>
                <ad:value>WANTED</ad:value>
        </ad:ad-type>
        <cat:category id="14922001"/>
        <ad:email>notmyemail@email.com</ad:email>
        <ad:poster-contact-name>Connor</ad:poster-contact-name>
        <ad:account-id>1018657122</ad:account-id>
        <ad:ad-address>
                <types:zip-code>N5W0A6</types:zip-code>
        </ad:ad-address>
        <ad:price>
                <types:price-type>
                        <types:value>SPECIFIED_AMOUNT</types:value>
                </types:price-type>
                <types:amount>300</types:amount>
        </ad:price>
        <attr:attributes>
        </attr:attributes>
</ad:ad>`

Here is the Kijiji API error:

`OrderedDict([('api-base-error', OrderedDict([('@xmlns', 'http://www.ebayclassifiedsgroup.com/schema/types/v1'), ('@http-status-code', '400'), ('api-errors', None), ('api-debug-errors', None), ('api-field-errors', OrderedDict([('api-field-error', OrderedDict([('field-xpath', 'forsaleby'), ('api-errors', OrderedDict([('api-error', OrderedDict([('message', 'Please select a value for "For Sale By"')]))]))]))]))]))])`

Looks like it wants a for sale by field.  On the Kijiji site this is either Owner or Business.

**Comment by rybodiddly** [comment]
Ok thanks. So it looks like its due to a missing ad attribute. "For sale by", which is handled by the dynamic attribute builder. I can verify that it's missing for the category you're attempting to post this in. So thank you for bringing this bug to my attention. Will see if I can get it sorted quickly.

**Comment by rybodiddly** [comment]
problem found. working on solution.

**Comment by rybodiddly** [comment]
Solution has been committed. Wasn't actually my server code. Seems Kijiji recently updated the attributes for many of their ads. So had to reacquire. Thanks for catching that for me.  Let me know if it works. If so we'll mark this as closed.

**Comment by Connor2hd** [comment]
> Solution has been committed. Wasn't actually my server code. Seems Kijiji recently updated the attributes for many of their ads. So had to reacquire and upload all the new attributes. Thanks for catching that for me. Let me know if it works. If so we'll mark this as closed.

That fixed it, thanks a lot.
