### ISSUE TITLE
ImportError: bad magic number in 'kijijiapi': b'B\r\r\n'

### ISSUE THREAD

**Issue by KingAchu** [rybodiddly/Kijiji-Reposter#6]
I tried running server.py as stipulated but got this error;
ImportError: bad magic number in 'kijijiapi': b'B\r\r\n'

Any reason why such an error?

**Comment by rybodiddly** [comment]
the magic number is the first two bytes in the pyc bytecode file (i.e kijijiapi.pyc) that signifies to the interpreter that it is a bytecode file. Magic numbers in general are are hex values used to signify file types usually contained within the first few header bytes (i.e Java files use CAFE BABE). For whatever reason your python installation is having issues loading the pyc file and believes the magic number is incorrect. Anyways, I removed the pyc file altogether and just replaced it with the original py file. should work fine now. Download a fresh copy and give it a go.
